"use client";

import { useState } from "react";
import { Add, DeleteOutlineOutlined as DeleteOutline, KeyOutlined, SaveOutlined } from "@mui/icons-material";
import type { AuditLog, Department, Role, User } from "../api";

const roleLabels:Record<Role,string>={admin:"Администратор системы",director:"Директор",deputy:"Заместитель директора",manager:"Руководитель управления",expert:"Эксперт"};
export function AdminView({users,departments,logs,onCreate,onSave,onReset,onDelete,onCreateDepartment,onDeleteDepartment}:{users:User[];departments:Department[];logs:AuditLog[];onCreate:()=>void;onSave:(user:User)=>Promise<void>;onReset:(id:string,password:string)=>Promise<void>;onDelete:(id:string)=>Promise<void>;onCreateDepartment:(name:string)=>Promise<void>;onDeleteDepartment:(id:string)=>Promise<void>}){
  const [drafts,setDrafts]=useState<Record<string,User>>({});const [passwordFor,setPasswordFor]=useState<string|null>(null);const [password,setPassword]=useState("");const [departmentName,setDepartmentName]=useState("");
  const value=(user:User)=>drafts[user.id]??user;const change=(user:User,patch:Partial<User>)=>setDrafts(current=>({...current,[user.id]:{...value(user),...patch}}));
  return <><div className="pageTitle"><div><p>Системное управление</p><h1>Администрирование eTask</h1><p>Учётные записи, управления и технический журнал</p></div><button className="primaryButton" onClick={onCreate}><Add/> Новый пользователь</button></div>
    <section className="panel adminSection"><div className="panelHead"><div><h3>Пользователи</h3><p>Рабочие роли и доступ назначаются только здесь</p></div></div>
      <div className="adminUsers">{users.map(user=>{const draft=value(user);return <article className="adminUser" key={user.id}><div><b>{user.fullName}</b><small>{user.username} · {user.position}</small></div><select aria-label={`Роль ${user.fullName}`} value={draft.role} onChange={e=>change(user,{role:e.target.value as Role,departmentId:e.target.value==="admin"?null:draft.departmentId})}>{Object.entries(roleLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><select aria-label={`Управление ${user.fullName}`} value={draft.departmentId??""} disabled={draft.role==="admin"} onChange={e=>change(user,{departmentId:e.target.value||null})}><option value="">Без управления</option>{departments.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select aria-label={`Статус ${user.fullName}`} value={draft.status??"active"} onChange={e=>change(user,{status:e.target.value})}><option value="active">Активен</option><option value="vacation">Отсутствует</option><option value="disabled">Заблокирован</option></select><div className="rowActions"><button title="Сохранить" onClick={()=>onSave(draft)}><SaveOutlined/></button><button title="Сбросить пароль" onClick={()=>{setPasswordFor(user.id);setPassword("");}}><KeyOutlined/></button><button title="Удалить" onClick={()=>onDelete(user.id)}><DeleteOutline/></button></div></article>})}</div>
    </section>
    {passwordFor&&<section className="panel passwordReset" aria-label="Сброс пароля"><label>Новый временный пароль<input type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><button className="primaryButton" disabled={password.length<12} onClick={async()=>{await onReset(passwordFor,password);setPasswordFor(null);setPassword("");}}>Сохранить пароль</button><button className="outlineButton" onClick={()=>setPasswordFor(null)}>Отмена</button></section>}
    <section className="panel adminSection"><div className="panelHead"><div><h3>Управления</h3><p>Организационная структура департамента</p></div></div><form className="departmentForm" onSubmit={async e=>{e.preventDefault();await onCreateDepartment(departmentName);setDepartmentName("");}}><input required minLength={2} value={departmentName} onChange={e=>setDepartmentName(e.target.value)} placeholder="Название нового управления"/><button className="primaryButton" type="submit"><Add/> Добавить</button></form><div className="departmentList">{departments.map(item=><div key={item.id}><span>{item.name}</span><button title="Удалить управление" onClick={()=>onDeleteDepartment(item.id)}><DeleteOutline/></button></div>)}</div></section>
    <section className="panel adminSection"><div className="panelHead"><div><h3>Технический журнал</h3><p>Последние административные действия</p></div></div><div className="auditList">{logs.map(item=><div key={item.id}><b>{item.action}</b><span>{item.actor??"Система"} · {new Date(item.createdAt).toLocaleString("ru-RU")}</span><small>{item.targetType} {item.targetId??""} · {item.ip??"локально"}</small></div>)}{!logs.length&&<p className="emptyState">Записей пока нет</p>}</div></section>
  </>;
}
