"use client";

import { useEffect, useRef, useState } from "react";
import { Close, DeleteOutlineOutlined, DescriptionOutlined, SaveOutlined } from "@mui/icons-material";
import { Avatar, Dialog, DialogContent, IconButton } from "@mui/material";
import { api, type ApiTask, type Department, type Notification, type Priority, type Project, type TaskDetails, type User } from "../api";

const priorityClass:Record<Priority,string>={"Критический":"critical","Высокий":"high","Средний":"medium","Низкий":"low"};

function TaskEditor({task,currentUser,onSaved}:{task:ApiTask;currentUser:User;onSaved:()=>Promise<void>}){
  const [error,setError]=useState("");const expert=currentUser.role==="expert";
  return <form className="taskEditForm" onSubmit={async event=>{event.preventDefault();setError("");const values=Object.fromEntries(new FormData(event.currentTarget));const body=expert?{status:values.status}:{title:String(values.title),description:String(values.description),priority:values.priority,status:values.status,deadline:values.deadline?new Date(String(values.deadline)).toISOString():null,assigneeId:values.assigneeId||null};try{await api.updateTask(task,body);await onSaved();}catch(problem){setError(problem instanceof Error?problem.message:"Не удалось сохранить задачу");}}}>
    {!expert&&<><label>Название<input name="title" defaultValue={task.title} required minLength={3}/></label><label className="wide">Описание<textarea name="description" defaultValue={task.description} maxLength={20000}/></label><label>Приоритет<select name="priority" defaultValue={task.priority}>{Object.keys(priorityClass).map(value=><option key={value}>{value}</option>)}</select></label><label>Дедлайн<input name="deadline" type="datetime-local" defaultValue={task.deadline?new Date(new Date(task.deadline).getTime()-new Date(task.deadline).getTimezoneOffset()*60000).toISOString().slice(0,16):""}/></label></>}
    {expert&&<label>Статус<select name="status" defaultValue="В работе"><option>В работе</option></select></label>}
    {error&&<p className="loginError wide" role="alert">{error}</p>}<button className="primaryButton" type="submit"><SaveOutlined/> Сохранить изменения</button>
  </form>;
}

export function TaskDialog({task,currentUser,users,onClose,onChanged,onDeleted}:{task:ApiTask|null;currentUser:User;users:User[];onClose:()=>void;onChanged:()=>Promise<void>|void;onDeleted:()=>Promise<void>|void}) {
  const [comment,setComment]=useState(""); const [error,setError]=useState(""); const fileRef=useRef<HTMLInputElement>(null);
  const [details,setDetails]=useState<TaskDetails|null>(null);
  useEffect(()=>{let active=true;if(task)api.taskDetails(task.id).then(value=>{if(active)setDetails(value);}).catch(problem=>{if(active)setError(problem instanceof Error?problem.message:"Ошибка загрузки");});return()=>{active=false;};},[task]);
  if(!task)return null;
  const reloadDetails=async()=>setDetails(await api.taskDetails(task.id));
  const targetUsers=users.filter(value=>value.status!=="disabled");
  const targets=currentUser.role==="director"?targetUsers.filter(value=>value.role==="deputy"||value.role==="manager"):currentUser.role==="deputy"?(task.status==="На согласовании заместителя"?targetUsers.filter(value=>value.role==="director"):targetUsers.filter(value=>value.role==="manager"&&value.departmentId===task.departmentId)):currentUser.role==="manager"?(task.status==="На проверке руководителя"?targetUsers.filter(value=>value.role==="deputy"):targetUsers.filter(value=>value.role==="expert"&&value.departmentId===task.departmentId)):targetUsers.filter(value=>value.role==="manager"&&value.departmentId===task.departmentId);
  const transfer=async(action:"assign"|"submit"|"return"|"approve"|"close",target?:User)=>{const reason=action==="return"?window.prompt("Укажите причину возврата:","")?.trim():undefined;if(action==="return"&&!reason){setError("Причина возврата обязательна");return;}try{await api.workflow(task,{action,targetAssigneeId:target?.id??null,reason});await onChanged();await reloadDetails();}catch(problem){setError(problem instanceof Error?problem.message:"Не удалось передать задачу");}};
  return <Dialog open maxWidth="md" fullWidth onClose={onClose} PaperProps={{className:"taskDialog"}}><DialogContent><div className="dialogTop"><span className="projectTag"><i/>{task.project}</span><div className="dialogActions">{currentUser.role!=="expert"&&<button className="dangerButton" onClick={async()=>{if(window.confirm("Удалить задачу без возможности восстановления?")){await api.deleteTask(task.id);await onDeleted();onClose();}}}><DeleteOutlineOutlined/> Удалить</button>}<IconButton onClick={onClose} aria-label="Закрыть"><Close/></IconButton></div></div><div className="dialogGrid"><main><small className="taskId">ЗАДАЧА #{task.id}</small><h2>{task.title}</h2><p className="taskDesc">{task.description||"Описание не добавлено"}</p>
    <section className="workflowPanel"><strong>Текущий этап: {details?.task.currentStage??task.currentStage}</strong><span>Исполнитель: {details?.task.assignee??task.assignee??"Не назначен"}</span><span>На этапе: {details?.task.stageStartedAt?new Date(details.task.stageStartedAt).toLocaleString("ru-RU"):"—"} · Возвратов: {details?.task.returnCount??task.returnCount}</span>{(details?.task.returnReason||task.returnReason)&&<span className="redText">Причина возврата: {details?.task.returnReason??task.returnReason}</span>}<div className="workflowActions">{targets.map(target=><button key={target.id} className="outlineButton" onClick={()=>transfer(currentUser.role==="expert"?"submit":currentUser.role==="manager"&&target.role==="deputy"?"approve":currentUser.role==="deputy"&&target.role==="director"?"submit":"assign",target)}>{currentUser.role==="manager"&&target.role==="deputy"?"Согласовать и передать":"Передать"}: {target.fullName}</button>)}{currentUser.role==="manager"&&task.status==="На проверке руководителя"&&<button className="outlineButton" onClick={()=>transfer("return",targetUsers.find(value=>value.role==="expert"&&value.departmentId===task.departmentId))}>Вернуть эксперту</button>}{currentUser.role==="deputy"&&task.status==="На согласовании заместителя"&&<button className="outlineButton" onClick={()=>transfer("return",targetUsers.find(value=>value.role==="director"))}>Вернуть директору</button>}{currentUser.role==="director"&&task.status==="На утверждении директора"&&<button className="outlineButton" onClick={()=>transfer("return",targetUsers.find(value=>value.role==="deputy"))}>Вернуть заместителю</button>}{currentUser.role==="director"&&task.status==="На утверждении директора"&&<button className="primaryButton" onClick={()=>transfer("approve")}>Принять исполнение</button>}{currentUser.role==="director"&&task.status==="Выполнена"&&<button className="primaryButton" onClick={()=>transfer("close")}>Закрыть задачу</button>}</div></section>
    <TaskEditor task={task} currentUser={currentUser} onSaved={async()=>{await onChanged();onClose();}}/>
    <h3>Чек-лист <span>{details?.checklist.filter(x=>x.completed).length??0}/{details?.checklist.length??0}</span></h3>{details?.checklist.map(item=><label className="check" key={item.id}><input type="checkbox" checked={item.completed} onChange={async e=>{await api.updateChecklistItem(task.id,item.id,e.target.checked);await reloadDetails();}}/><span>{item.title}</span><button type="button" className="iconDanger" aria-label={`Удалить пункт ${item.title}`} onClick={async()=>{await api.deleteChecklistItem(task.id,item.id);await reloadDetails();}}><DeleteOutlineOutlined/></button></label>)}<form className="commentInput" onSubmit={async event=>{event.preventDefault();const value=String(new FormData(event.currentTarget).get("title")??"");await api.addChecklistItem(task.id,value);event.currentTarget.reset();await reloadDetails();}}><input name="title" aria-label="Новый пункт чек-листа" required placeholder="Добавить пункт"/><button>Добавить</button></form>
    <h3>Подзадачи <span>{details?.subtasks.length??0}</span></h3>{details?.subtasks.map(item=><div className="activityRow" key={item.id}><div><strong>{item.title}</strong><p>{item.status}</p></div></div>)}
    <h3>Комментарии <span>{details?.comments.length??task.comments}</span></h3>{details?.comments.map(item=><div className="comment" key={item.id}><Avatar>{item.initials}</Avatar><div><b>{item.author}</b><small>{new Date(item.createdAt).toLocaleString("ru-RU")}</small><p>{item.body}</p></div>{(currentUser.role!=="expert"||item.authorId===currentUser.id)&&<button type="button" className="iconDanger" aria-label={`Удалить комментарий ${item.author}`} onClick={async()=>{await api.deleteComment(task.id,item.id);await reloadDetails();}}><DeleteOutlineOutlined/></button>}</div>)}<form className="commentInput" onSubmit={async event=>{event.preventDefault();setError("");try{await api.comment(task.id,comment);setComment("");await reloadDetails();onChanged();}catch(error){setError(error instanceof Error?error.message:"Ошибка");}}}><Avatar>{task.initials??"—"}</Avatar><input aria-label="Комментарий" placeholder="Написать комментарий..." value={comment} onChange={e=>setComment(e.target.value)} required minLength={1}/><button>Отправить</button></form>
    <h3>История изменений</h3>{details?.history.map(item=><div className="activityRow" key={item.id}><div><strong>{item.author??"Система"}</strong><p>{item.action} · {new Date(item.createdAt).toLocaleString("ru-RU")}</p></div></div>)}{error&&<p className="loginError" role="alert">{error}</p>}</main><aside><h4>Детали</h4><dl><dt>Статус</dt><dd><span className="statusSelect">{task.status}</span></dd><dt>Приоритет</dt><dd><span className={`priority ${priorityClass[task.priority]}`}>{task.priority}</span></dd><dt>Исполнитель</dt><dd className="assignee"><Avatar>{task.initials??"—"}</Avatar>{task.assignee??"Не назначен"}</dd><dt>Управление</dt><dd>{task.department}</dd><dt>Дедлайн</dt><dd>{task.deadline?new Date(task.deadline).toLocaleString("ru-RU"):"Без срока"}</dd><dt>Создана</dt><dd>{new Date(task.createdAt).toLocaleDateString("ru-RU")}</dd></dl><h4>Вложения <span>{details?.attachments.length??task.files}</span></h4>{details?.attachments.map(file=><div className="fileRow" key={file.id}><a className="file" href={`/api/files/${file.id}`}><DescriptionOutlined/><div><b>{file.name}</b><small>{Math.ceil(file.size/1024)} КБ</small></div></a>{(currentUser.role!=="expert"||file.uploaderId===currentUser.id)&&<button type="button" className="iconDanger" aria-label={`Удалить файл ${file.name}`} onClick={async()=>{await api.deleteAttachment(file.id);await reloadDetails();onChanged();}}><DeleteOutlineOutlined/></button>}</div>)}<input ref={fileRef} className="srOnly" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.txt" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError("");try{await api.upload(task.id,file);await reloadDetails();onChanged();}catch(error){setError(error instanceof Error?error.message:"Ошибка загрузки");}finally{e.target.value="";}}}/><button className="upload" onClick={()=>fileRef.current?.click()}><DescriptionOutlined/> Добавить файл</button></aside></div></DialogContent></Dialog>;
}

type CreateKind="task"|"project"|"user";
export function CreateDialog({kind,open,onClose,projects,users,departments,onCreated}:{kind:CreateKind;open:boolean;onClose:()=>void;projects:Project[];users:User[];departments:Department[];onCreated:()=>void}) {
  const [error,setError]=useState("");
  return <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth><DialogContent><div className="dialogTop"><h2>{kind==="task"?"Новая задача":kind==="project"?"Новый проект":"Новый сотрудник"}</h2><IconButton onClick={onClose} aria-label="Закрыть"><Close/></IconButton></div><form className="createForm" onSubmit={async event=>{event.preventDefault();setError("");const values=Object.fromEntries(new FormData(event.currentTarget));try{
    if(kind==="project")await api.createProject({name:String(values.name),description:String(values.description),color:String(values.color)});
    if(kind==="task")await api.createTask({title:String(values.title),description:String(values.description),projectId:String(values.projectId),departmentId:String(values.departmentId),assigneeId:values.assigneeId?String(values.assigneeId):null,priority:String(values.priority) as Priority,deadline:values.deadline?new Date(String(values.deadline)).toISOString():null});
    if(kind==="user")await api.createUser({username:values.username,password:values.password,fullName:values.fullName,position:values.position,departmentId:values.departmentId||null,role:values.role,email:values.email||null,phone:values.phone||null,initials:values.initials});
    onCreated();onClose();event.currentTarget.reset();
  }catch(error){setError(error instanceof Error?error.message:"Ошибка сохранения");}}}>
    {kind==="project"&&<><label>Название<input name="name" required minLength={2}/></label><label>Описание<textarea name="description" maxLength={5000}/></label><label>Цвет<input name="color" type="color" defaultValue="#246BCE"/></label></>}
    {kind==="task"&&<><label>Название<input name="title" required minLength={3}/></label><label>Описание<textarea name="description" maxLength={20000}/></label><label>Проект<select name="projectId" required><option value="">Выберите проект</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Управление<select name="departmentId" required><option value="">Выберите управление</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Исполнитель<select name="assigneeId"><option value="">Не назначен</option>{users.map(x=><option key={x.id} value={x.id}>{x.fullName}</option>)}</select></label><label>Приоритет<select name="priority" defaultValue="Средний">{Object.keys(priorityClass).map(x=><option key={x}>{x}</option>)}</select></label><label>Дедлайн<input name="deadline" type="datetime-local"/></label></>}
    {kind==="user"&&<><label>ФИО<input name="fullName" required minLength={3}/></label><label>Логин<input name="username" required pattern="[a-zA-Z0-9._-]+" minLength={3}/></label><label>Временный пароль<input name="password" type="password" required minLength={12} autoComplete="new-password"/></label><label>Должность<input name="position" required/></label><label>Управление<select name="departmentId"><option value="">Без управления</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Роль<select name="role">{[["expert","Эксперт"],["manager","Руководитель управления"],["deputy","Заместитель директора"],["director","Директор"],["admin","Администратор системы"]].map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Инициалы<input name="initials" required maxLength={4}/></label><label>Email<input name="email" type="email"/></label><label>Телефон<input name="phone"/></label></>}
    {error&&<p className="loginError" role="alert">{error}</p>}<button className="primaryButton" type="submit">Сохранить</button>
  </form></DialogContent></Dialog>;
}

export function SearchDialog({open,onClose,results}:{open:boolean;onClose:()=>void;results:Array<{type:string;id:string;label:string;context:string}>}){return <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth><DialogContent><div className="dialogTop"><h2>Результаты поиска</h2><IconButton onClick={onClose} aria-label="Закрыть"><Close/></IconButton></div>{results.length?results.map(result=><div className="activityRow" key={`${result.type}-${result.id}`}><div><small>{result.type}</small><strong>{result.label}</strong><p>{result.context}</p></div></div>):<p className="emptyState">Ничего не найдено</p>}</DialogContent></Dialog>}

export function NotificationsDialog({open,onClose,items,onRead}:{open:boolean;onClose:()=>void;items:Notification[];onRead:(item:Notification)=>void}){return <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth><DialogContent><div className="dialogTop"><h2>Уведомления</h2><IconButton onClick={onClose} aria-label="Закрыть"><Close/></IconButton></div>{items.length?items.map(item=><button className={`activityRow notification ${item.readAt?"":"unread"}`} key={item.id} onClick={()=>onRead(item)}><div><strong>{item.message}</strong><p>{new Date(item.createdAt).toLocaleString("ru-RU")}</p></div></button>):<p className="emptyState">Новых уведомлений нет</p>}</DialogContent></Dialog>}
