"use client";

import { useState } from "react";
import { Add, CalendarMonthOutlined, DeleteOutlineOutlined, EditOutlined, FolderOutlined, Search, Tune, WarningAmber } from "@mui/icons-material";
import { Avatar, LinearProgress } from "@mui/material";
import { api, type ApiTask, type CalendarTask, type DashboardData, type Project, type User } from "../api";

export function Loading(){return <div className="emptyState" role="status">Загрузка данных…</div>}
export function Empty({children="Данных пока нет"}:{children?:string}){return <div className="emptyState">{children}</div>}

export function Dashboard({data,tasks,goBoard}:{data:DashboardData|null;tasks:ApiTask[];goBoard:()=>void}) {
  if(!data)return <Loading/>;
  const metrics=[["Всего задач",data.total,"total"],["В работе",data.inProgress,"work"],["Просрочено",data.overdue,"late"],["Выполнено",data.completed,"done"],["На проверке",data.review,"review"]];
  const urgent=tasks.filter(task=>task.deadline&&task.status!=="Выполнена"&&task.status!=="Закрыта").sort((a,b)=>String(a.deadline).localeCompare(String(b.deadline))).slice(0,5);
  return <><div className="pageTitle"><div><p>{new Date().toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}</p><h1>Обзор работы</h1><p>Актуальные показатели вашего рабочего пространства.</p></div></div>
    <div className="metricGrid">{metrics.map(([label,value,kind])=><div className={`metricCard ${kind}`} key={label}><div className="metricIcon"><WarningAmber/></div><div><span>{label}</span><strong>{value}</strong></div></div>)}</div>
    <section className="panel deadlines"><div className="panelHead"><div><h3>Ближайшие сроки</h3><p>Задачи, требующие внимания</p></div><CalendarMonthOutlined/></div>{urgent.length?urgent.map(task=><button className="deadline compact" key={task.id} onClick={goBoard}><strong>{task.title}</strong><small>{task.assignee??"Не назначен"} · {new Date(task.deadline!).toLocaleString("ru-RU")}</small></button>):<Empty>Нет ближайших сроков</Empty>}<button className="fullLink" onClick={goBoard}>Открыть все задачи →</button></section>
  </>;
}

export function Projects({projects,editable,onCreate,onChanged}:{projects:Project[];editable:boolean;onCreate?:()=>void;onChanged:()=>Promise<void>}) {
  const [editing,setEditing]=useState<Project|null>(null); const [boardProject,setBoardProject]=useState<string|null>(null); const [error,setError]=useState("");
  return <><div className="pageTitle"><div><p>Рабочее пространство</p><h1>Проекты</h1><p>Все направления цифровизации и государственных услуг</p></div>{onCreate&&<button className="primaryButton" onClick={onCreate}><Add/> Новый проект</button>}</div>
    {error&&<p className="loginError" role="alert">{error}</p>}{projects.length?<div className="projectGrid">{projects.map(project=>{const progress=project.tasks?Math.round(project.completed/project.tasks*100):0;return <article className="projectCard" key={project.id}><div className="projectCover" style={{background:`linear-gradient(135deg,${project.color},${project.color}cc)`}}><FolderOutlined/>{editable&&<span className="projectActions"><button aria-label={`Редактировать ${project.name}`} onClick={()=>setEditing(project)}><EditOutlined/></button><button aria-label={`Удалить ${project.name}`} onClick={async()=>{if(!window.confirm(`Удалить проект «${project.name}»?`))return;try{await api.deleteProject(project.id);await onChanged();}catch(problem){setError(problem instanceof Error?problem.message:"Не удалось удалить проект");}}}><DeleteOutlineOutlined/></button></span>}</div><div className="projectContent"><h3>{project.name}</h3><p>{project.description}</p><small>{project.tasks} задач</small><LinearProgress variant="determinate" value={progress}/><footer><b>{progress}%</b><span>{project.completed} выполнено</span></footer><div className="boardsList">{project.boards?.map(board=><span key={board.id}>{board.name}{editable&&<button aria-label={`Удалить доску ${board.name}`} onClick={async()=>{if(window.confirm(`Удалить доску «${board.name}»?`)){await api.deleteBoard(board.id);await onChanged();}}}>×</button>}</span>)}</div>{editable&&<button className="outlineButton" onClick={()=>setBoardProject(project.id)}><Add/> Добавить доску</button>}</div></article>})}</div>:<Empty>Проекты ещё не созданы</Empty>}
    {editing&&<form className="inlineEditor panel" onSubmit={async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{await api.updateProject(editing.id,{name:values.name,description:values.description,color:values.color});setEditing(null);await onChanged();}catch(problem){setError(problem instanceof Error?problem.message:"Не удалось изменить проект");}}}><h3>Редактирование проекта</h3><label>Название<input name="name" defaultValue={editing.name} required minLength={2}/></label><label>Описание<textarea name="description" defaultValue={editing.description}/></label><label>Цвет<input name="color" type="color" defaultValue={editing.color}/></label><div><button type="button" className="outlineButton" onClick={()=>setEditing(null)}>Отмена</button><button className="primaryButton">Сохранить</button></div></form>}
    {boardProject&&<form className="inlineEditor panel" onSubmit={async event=>{event.preventDefault();const name=String(new FormData(event.currentTarget).get("name"));try{await api.createBoard(boardProject,name);setBoardProject(null);await onChanged();}catch(problem){setError(problem instanceof Error?problem.message:"Не удалось создать доску");}}}><h3>Новая доска</h3><label>Название<input name="name" required minLength={2} autoFocus/></label><div><button type="button" className="outlineButton" onClick={()=>setBoardProject(null)}>Отмена</button><button className="primaryButton">Создать</button></div></form>}
  </>;
}

export function CalendarView({events,users,onFilter}:{events:CalendarTask[];users:User[];onFilter:(id?:string)=>void}) {
  const grouped=events.reduce<Record<string,CalendarTask[]>>((result,event)=>{const key=event.deadline?new Date(event.deadline).toLocaleDateString("ru-RU"):"Без срока";(result[key]??=[]).push(event);return result;},{});
  return <><div className="pageTitle"><div><p>Планирование</p><h1>Календарь</h1><p>Дедлайны на ближайшие 31 день</p></div><label className="outlineButton"><Tune/> <select aria-label="Фильтр по сотруднику" onChange={e=>onFilter(e.target.value||undefined)}><option value="">Все сотрудники</option>{users.map(user=><option value={user.id} key={user.id}>{user.fullName}</option>)}</select></label></div>
    <section className="calendar panel">{Object.keys(grouped).length?Object.entries(grouped).map(([date,items])=><div className="deadlineGroup" key={date}><b>{date} <span>{items.length}</span></b>{items.map(item=><div className="deadline compact" key={item.id}><strong>{item.title}</strong><small>{item.assignee??"Не назначен"} · {item.status}</small></div>)}</div>):<Empty>В выбранном периоде задач нет</Empty>}</section>
  </>;
}

export function People({users,canCreate,onCreate}:{users:User[];canCreate:boolean;onCreate:()=>void}) {
  const [query,setQuery]=useState(""); const visible=users.filter(user=>`${user.fullName} ${user.position} ${user.department}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="pageTitle"><div><p>Администрирование</p><h1>Сотрудники</h1><p>{users.length} сотрудников</p></div>{canCreate&&<button className="primaryButton" onClick={onCreate}><Add/> Добавить сотрудника</button>}</div><section className="panel peopleTable"><div className="tableTools"><label className="search small"><Search/><input aria-label="Найти сотрудника" placeholder="Найти сотрудника..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="thead"><span>Сотрудник</span><span>Должность</span><span>Управление</span><span>Роль</span><span>Статус</span><span/></div>{visible.map((user,index)=><div className="trow" key={user.id}><span className="person"><Avatar className={`av${index%4}`}>{user.initials??"—"}</Avatar><span><b>{user.fullName}</b><small>{user.email??"—"}</small></span></span><span>{user.position}</span><span>{user.department??"—"}</span><span><i className="rolePill">{user.role}</i></span><span><i className={user.status==="active"?"statusActive":"statusAway"}>{user.status==="active"?"Активен":"Неактивен"}</i></span><span/></div>)}</section></>;
}

export function Structure({users}:{users:User[]}) {
  const [selected,setSelected]=useState<User|null>(users[0]??null); const departments=Array.from(new Set(users.map(user=>user.department).filter(Boolean)));
  return <><div className="pageTitle"><div><p>Организация</p><h1>Структура департамента</h1><p>Интерактивная схема сотрудников</p></div></div><div className="structureLayout"><section className="org panel"><div className="departments">{departments.map((department,index)=><div className="department" key={department}><h3><span>{index+1}</span>{department}</h3><div className="experts">{users.filter(user=>user.department===department).map(user=><button key={user.id} onClick={()=>setSelected(user)} className="orgNode"><Avatar>{user.initials??"—"}</Avatar><span><b>{user.fullName}</b><small>{user.position}</small></span></button>)}</div></div>)}</div></section>{selected&&<aside className="profileCard panel"><Avatar>{selected.initials??"—"}</Avatar><h2>{selected.fullName}</h2><p>{selected.position}</p><span className={selected.status==="active"?"statusActive":"statusAway"}>● {selected.status==="active"?"На работе":"Неактивен"}</span><dl><dt>Управление</dt><dd>{selected.department??"—"}</dd><dt>Email</dt><dd>{selected.email??"—"}</dd><dt>Телефон</dt><dd>{selected.phone??"—"}</dd></dl></aside>}</div></>;
}
