import { Router } from "express";
import { pool } from "../db.js";
import { allow, authenticate } from "../middleware/auth.js";
import type { AuthRequest } from "../types.js";

export const workspaceRouter=Router(); workspaceRouter.use(authenticate);
const scoped=(req:AuthRequest,alias="t")=>req.user!.role==="expert"?{sql:` AND ${alias}.assignee_id=$1`,args:[req.user!.id]}:req.user!.role==="manager"?{sql:` AND ${alias}.department_id=$1`,args:[req.user!.departmentId]}:{sql:"",args:[]};

workspaceRouter.get("/projects",async(req:AuthRequest,res)=>{const s=scoped(req);const {rows}=await pool.query(`SELECT p.id,p.name,p.description,p.color,count(t.id)::int AS tasks,count(t.id) FILTER(WHERE t.status='Выполнено')::int AS completed FROM projects p LEFT JOIN tasks t ON t.project_id=p.id ${s.sql.replace(" AND "," AND ")} GROUP BY p.id ORDER BY p.created_at DESC`,s.args);res.json(rows)});
workspaceRouter.post("/projects",allow("director","deputy"),async(req:AuthRequest,res)=>{const {rows}=await pool.query(`INSERT INTO projects(name,description,color,created_by) VALUES($1,$2,$3,$4) RETURNING *`,[req.body.name,req.body.description,req.body.color,req.user!.id]);res.status(201).json(rows[0])});
workspaceRouter.post("/projects/:projectId/boards",allow("director","deputy"),async(req,res)=>{const {rows}=await pool.query(`INSERT INTO boards(project_id,name) VALUES($1,$2) RETURNING *`,[req.params.projectId,req.body.name]);res.status(201).json(rows[0])});

workspaceRouter.get("/dashboard",async(req:AuthRequest,res)=>{const s=scoped(req);const {rows}=await pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status='В работе')::int in_progress,count(*) FILTER(WHERE deadline<now() AND status<>'Выполнено')::int overdue,count(*) FILTER(WHERE status='Выполнено')::int completed,count(*) FILTER(WHERE status='На проверке')::int review FROM tasks t WHERE true ${s.sql}`,s.args);res.json(rows[0])});
workspaceRouter.get("/analytics",allow("director","deputy","manager"),async(req:AuthRequest,res)=>{const s=scoped(req);const {rows}=await pool.query(`SELECT d.name AS department,count(t.id)::int total,count(t.id) FILTER(WHERE t.status='Выполнено')::int completed,count(t.id) FILTER(WHERE t.deadline<now() AND t.status<>'Выполнено')::int overdue,round(avg(EXTRACT(EPOCH FROM(t.updated_at-t.created_at))/86400)::numeric,1) AS avg_days FROM departments d LEFT JOIN tasks t ON t.department_id=d.id WHERE true ${s.sql} GROUP BY d.id ORDER BY d.sort_order`,s.args);res.json(rows)});
workspaceRouter.get("/calendar",async(req:AuthRequest,res)=>{const s=scoped(req);const from=String(req.query.from??new Date().toISOString());const to=String(req.query.to??new Date(Date.now()+31*86400000).toISOString());const args=[...s.args,from,to];const {rows}=await pool.query(`SELECT t.id,t.title,t.deadline,t.status,u.full_name AS assignee FROM tasks t LEFT JOIN users u ON u.id=t.assignee_id WHERE t.deadline BETWEEN $${args.length-1} AND $${args.length} ${s.sql}`,args);res.json(rows)});
workspaceRouter.get("/search",async(req:AuthRequest,res)=>{const q=`%${String(req.query.q??"")}%`;const s=scoped(req);const args=[...s.args,q];const n=args.length;const {rows}=await pool.query(`SELECT 'task' AS type,t.id::text,t.title AS label,t.description AS context FROM tasks t WHERE (t.title ILIKE $${n} OR t.description ILIKE $${n}) ${s.sql} UNION ALL SELECT 'project',p.id::text,p.name,p.description FROM projects p WHERE p.name ILIKE $${n} LIMIT 30`,args);res.json(rows)});
