"use client";

import { useEffect, useMemo, useState } from "react";
import { api, session } from "./api";
import { DndProvider, useDrag, useDrop } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import {
  Add, AnalyticsOutlined, AssignmentTurnedInOutlined, CalendarMonthOutlined,
  CheckCircleOutlineOutlined, Close, DashboardOutlined, DescriptionOutlined, FolderOutlined,
  GroupsOutlined, KeyboardArrowDown, Logout, Menu, MoreHoriz, NotificationsNone,
  Search, SettingsOutlined, SpaceDashboardOutlined, TaskAlt, Tune, WarningAmber,
} from "@mui/icons-material";
import { Avatar, Badge, Button, Dialog, DialogContent, IconButton, LinearProgress, Tooltip } from "@mui/material";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";

type View = "dashboard" | "boards" | "projects" | "calendar" | "analytics" | "people" | "structure";
type Status = "Новые" | "В работе" | "На согласовании" | "На проверке" | "Выполнено";
type Priority = "Критический" | "Высокий" | "Средний" | "Низкий";
type Task = { id:number; title:string; status:Status; priority:Priority; project:string; assignee:string; initials:string; due:string; comments:number; files:number; progress?:number; description:string; department:string; };

const nav: {id:View; label:string; icon:React.ReactNode}[] = [
  {id:"dashboard",label:"Обзор",icon:<DashboardOutlined/>}, {id:"boards",label:"Мои доски",icon:<SpaceDashboardOutlined/>},
  {id:"projects",label:"Проекты",icon:<FolderOutlined/>}, {id:"calendar",label:"Календарь",icon:<CalendarMonthOutlined/>},
  {id:"analytics",label:"Аналитика",icon:<AnalyticsOutlined/>}, {id:"people",label:"Сотрудники",icon:<GroupsOutlined/>},
  {id:"structure",label:"Структура",icon:<AccountTreeIcon/>},
];

const initialTasks: Task[] = [
  {id:241,title:"Согласовать техническую архитектуру ГИСС",status:"Новые",priority:"Критический",project:"Разработка ГИСС",assignee:"Айдана С.",initials:"АС",due:"Сегодня, 18:00",comments:6,files:3,progress:20,description:"Подготовить и согласовать целевую архитектуру платформы с учетом замечаний Комитета и QazTech.",department:"Управление цифровизации"},
  {id:238,title:"Актуализировать реестр государственных услуг",status:"Новые",priority:"Высокий",project:"Государственные услуги",assignee:"Данияр К.",initials:"ДК",due:"24 июл.",comments:3,files:1,description:"Проверить полноту реестра и обновить статусы услуг по ответственным подразделениям.",department:"Управление государственных услуг"},
  {id:230,title:"Подготовить протокол интеграции с E-Fish",status:"В работе",priority:"Средний",project:"E-Fish",assignee:"Мадина Т.",initials:"МТ",due:"25 июл.",comments:8,files:4,progress:65,description:"Свести замечания участников и подготовить финальный протокол интеграционного взаимодействия.",department:"Управление цифровизации"},
  {id:229,title:"Миграция справочников на платформу QazTech",status:"В работе",priority:"Высокий",project:"Миграция на QazTech",assignee:"Арман Б.",initials:"АБ",due:"Сегодня",comments:12,files:2,progress:48,description:"Проверить схемы данных и завершить перенос пилотного набора справочников.",department:"Управление сопровождения ИС"},
  {id:224,title:"Настроить межведомственный обмен ИСЖ",status:"На согласовании",priority:"Средний",project:"ИСЖ",assignee:"Ерлан Н.",initials:"ЕН",due:"28 июл.",comments:5,files:5,progress:82,description:"Согласовать состав данных и регламент обмена с заинтересованными органами.",department:"Управление цифровизации"},
  {id:219,title:"Проверить отчет по качеству электронных услуг",status:"На проверке",priority:"Высокий",project:"Государственные услуги",assignee:"Жанар А.",initials:"ЖА",due:"23 июл.",comments:9,files:2,progress:100,description:"Провести итоговую проверку отчета и оформить решение о приемке.",department:"Управление государственных услуг"},
  {id:211,title:"Обновить дорожную карту ЕАСУ",status:"Выполнено",priority:"Низкий",project:"ЕАСУ",assignee:"Алихан Р.",initials:"АР",due:"21 июл.",comments:4,files:1,progress:100,description:"Дорожная карта обновлена с учетом контрольных сроков второго полугодия.",department:"Управление сопровождения ИС"},
];

const statuses:Status[]=["Новые","В работе","На согласовании","На проверке","Выполнено"];
const priorityClass:Record<Priority,string>={"Критический":"critical","Высокий":"high","Средний":"medium","Низкий":"low"};
const projects=[
  ["Разработка ГИСС","Платформа геоинформационного обеспечения","12 задач","#246BCE"],
  ["Миграция на QazTech","Переход информационных систем","9 задач","#7556D8"],
  ["ЕАСУ","Единая аналитическая система управления","7 задач","#2E70C9"],
  ["ИСЖ","Информационная система животноводства","14 задач","#E49A33"],
  ["E-Fish","Цифровизация рыбного хозяйства","6 задач","#1E9BB5"],
  ["Внутренние поручения","Организационные и контрольные задачи","18 задач","#77818F"],
];

function AccountTreeIcon(){return <span className="treeIcon">⌘</span>}

function TaskCard({task,onOpen}:{task:Task;onOpen:(t:Task)=>void}){
  const [{isDragging},drag]=useDrag(()=>({type:"TASK",item:{id:task.id},collect:m=>({isDragging:m.isDragging()})}),[task.id]);
  return <article ref={drag as never} className="taskCard" style={{opacity:isDragging?.45:1}} onClick={()=>onOpen(task)} data-testid={`task-${task.id}`}>
    <div className="taskTop"><span className={`priority ${priorityClass[task.priority]}`}>{task.priority}</span><MoreHoriz fontSize="small"/></div>
    <h4>{task.title}</h4><span className="projectTag"><i style={{background:projects.find(p=>p[0]===task.project)?.[3]||"#246BCE"}}/>{task.project}</span>
    {task.progress!==undefined&&<div className="progressRow"><LinearProgress variant="determinate" value={task.progress}/><small>{task.progress}%</small></div>}
    <div className="taskMeta"><span className={task.due.includes("Сегодня")?"due urgent":"due"}>◷ {task.due}</span><span className="counts">◌ {task.comments} &nbsp;▱ {task.files}</span><Avatar className="miniAvatar">{task.initials}</Avatar></div>
  </article>
}

function Column({status,tasks,move,onOpen}:{status:Status;tasks:Task[];move:(id:number,s:Status)=>void;onOpen:(t:Task)=>void}){
  const [{over},drop]=useDrop(()=>({accept:"TASK",drop:(item:{id:number})=>move(item.id,status),collect:m=>({over:m.isOver()})}),[status]);
  return <section ref={drop as never} className={`kanbanColumn ${over?"over":""}`}><header><span className={`statusDot s${statuses.indexOf(status)}`}/><strong>{status}</strong><b>{tasks.length}</b><IconButton size="small"><MoreHoriz/></IconButton></header><div className="columnBody">{tasks.map(t=><TaskCard key={t.id} task={t} onOpen={onOpen}/>)}<button className="addTask"><Add/> Добавить задачу</button></div></section>
}

function Header({onMenu}:{onMenu:()=>void}){return <header className="topbar"><IconButton className="mobileMenu" onClick={onMenu}><Menu/></IconButton><div className="search"><Search/><input aria-label="Глобальный поиск" placeholder="Поиск задач, проектов, сотрудников..."/><kbd>⌘ K</kbd></div><div className="topActions"><button className="quick"><Add/> Создать</button><Tooltip title="Уведомления"><IconButton><Badge color="error" variant="dot"><NotificationsNone/></Badge></IconButton></Tooltip><span className="divider"/><Avatar className="avatar">КЖ</Avatar><div className="profile"><strong>Канат Жумабаев</strong><span>Директор департамента</span></div><KeyboardArrowDown/></div></header>}

function Sidebar({view,setView,open,onLogout}:{view:View;setView:(v:View)=>void;open:boolean;onLogout:()=>void}){return <aside className={`sidebar ${open?"open":""}`}><div className="brand"><div className="brandMark"><span>e</span></div><div><b>eTask</b><small>Управление задачами</small></div></div><nav>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}>{n.icon}<span>{n.label}</span>{n.id==="boards"&&<em>12</em>}</button>)}</nav><div className="sideBottom"><button><SettingsOutlined/><span>Настройки</span></button><button onClick={onLogout}><Logout/><span>Выйти</span></button><div className="helpCard"><span>?</span><b>Нужна помощь?</b><small>База знаний и поддержка</small><button>Открыть центр помощи</button></div></div></aside>}

function Dashboard({goBoard}:{goBoard:()=>void}){const metrics=[["Всего задач","128","+12 за месяц","total"],["В работе","34","27% от общего","work"],["Просрочено","7","Требуют внимания","late"],["Выполнено","76","+18% к прошлому","done"],["На проверке","11","Ожидают решения","review"]]; return <>
  <div className="pageTitle"><div><p>Среда, 22 июля</p><h1>Доброе утро, Канат! <span>👋</span></h1><p>Вот что происходит в департаменте сегодня.</p></div><button className="outlineButton"><Tune/> Настроить обзор</button></div>
  <div className="metricGrid">{metrics.map((m,i)=><div className={`metricCard ${m[3]}`} key={m[0]}><div className="metricIcon">{[<AssignmentTurnedInOutlined/>,<DescriptionOutlined/>,<WarningAmber/>,<TaskAlt/>,<CheckCircleOutlineOutlined/>][i]}</div><div><span>{m[0]}</span><strong>{m[1]}</strong><small>{m[2]}</small></div></div>)}</div>
  <div className="dashGrid"><section className="panel activity"><div className="panelHead"><div><h3>Последние изменения</h3><p>Активность по всем проектам</p></div><button>Все изменения →</button></div>{[
    ["АС","Айдана Сарсенова","переместила задачу","Согласовать архитектуру ГИСС","в На проверке","5 мин."],
    ["ДК","Данияр Касымов","добавил комментарий к задаче","Реестр государственных услуг","","24 мин."],
    ["МТ","Мадина Тлеубаева","прикрепила документ","Протокол интеграции E-Fish","","1 ч."],
    ["КЖ","Вы","изменили срок задачи","Миграция справочников QazTech","на сегодня","2 ч."],
  ].map((a,i)=><div className="activityRow" key={i}><Avatar className={`avatar av${i}`}>{a[0]}</Avatar><div><p><b>{a[1]}</b> {a[2]}</p><strong>{a[3]}</strong> <span>{a[4]}</span></div><time>{a[5]}</time></div>)}</section>
  <section className="panel deadlines"><div className="panelHead"><div><h3>Сроки</h3><p>Требуют вашего внимания</p></div><CalendarMonthOutlined/></div><div className="deadlineGroup"><b><i className="redDot"/> Сегодня <span>3</span></b>{initialTasks.slice(0,2).map(t=><div className="deadline" key={t.id}><span className={`priority ${priorityClass[t.priority]}`}>{t.priority}</span><strong>{t.title}</strong><small>{t.assignee} · {t.due}</small></div>)}</div><div className="deadlineGroup"><b><i className="amberDot"/> Ближайшие 7 дней <span>8</span></b>{initialTasks.slice(2,4).map(t=><div className="deadline compact" key={t.id}><strong>{t.title}</strong><small>{t.assignee} · {t.due}</small></div>)}</div><button className="fullLink" onClick={goBoard}>Открыть все задачи →</button></section></div>
  <section className="projectsStrip"><div className="sectionTitle"><div><h3>Активные проекты</h3><p>Проекты с ближайшими контрольными точками</p></div><button>Все проекты →</button></div><div className="projectMiniGrid">{projects.slice(0,4).map((p,i)=><div className="projectMini" key={p[0]}><div className="folderTile" style={{background:p[3]}}><FolderOutlined/></div><div><h4>{p[0]}</h4><small>{p[2]} · {11-i*2} участников</small></div><b>{[68,45,81,57][i]}%</b><LinearProgress variant="determinate" value={[68,45,81,57][i]}/></div>)}</div></section>
  </>}

function Boards({tasks,setTasks,onOpen}:{tasks:Task[];setTasks:(t:Task[])=>void;onOpen:(t:Task)=>void}){const move=(id:number,status:Status)=>{setTasks(tasks.map(t=>t.id===id?{...t,status}:t));if(session.get())api.moveTask(id,status).catch(()=>setTasks(tasks))};return <><div className="boardHero"><div><div className="breadcrumb">Проекты / Разработка ГИСС</div><h1>Поручения Министра <span className="star">☆</span></h1><p>Контроль исполнения поручений и протокольных решений</p></div><div className="boardPeople"><span><Avatar>КЖ</Avatar><Avatar>АС</Avatar><Avatar>ДК</Avatar><Avatar>+6</Avatar></span><button className="outlineButton">Поделиться</button><button className="primaryButton"><Add/> Задача</button></div></div><div className="boardTools"><button><Tune/> Фильтры <b>2</b></button><button>Все исполнители <KeyboardArrowDown/></button><button>Все приоритеты <KeyboardArrowDown/></button><span/><button><Search/></button><button><MoreHoriz/></button></div><DndProvider backend={HTML5Backend}><div className="kanban">{statuses.map(s=><Column key={s} status={s} tasks={tasks.filter(t=>t.status===s)} move={move} onOpen={onOpen}/>)}</div></DndProvider></>}

function Projects(){return <><div className="pageTitle"><div><p>Рабочее пространство</p><h1>Проекты</h1><p>Все направления цифровизации и государственных услуг</p></div><button className="primaryButton"><Add/> Новый проект</button></div><div className="projectGrid">{projects.map((p,i)=><article className="projectCard" key={p[0]}><div className="projectCover" style={{background:`linear-gradient(135deg,${p[3]},${p[3]}cc)`}}><FolderOutlined/><span>{String(i+1).padStart(2,"0")}</span></div><div className="projectContent"><h3>{p[0]}</h3><p>{p[1]}</p><div className="members"><span><Avatar>АС</Avatar><Avatar>ДК</Avatar><Avatar>+{i+3}</Avatar></span><small>{p[2]}</small></div><LinearProgress variant="determinate" value={[68,45,81,57,36,74][i]}/><footer><b>{[68,45,81,57,36,74][i]}%</b><span>Обновлено {i+1} ч. назад</span></footer></div></article>)}</div></>}

function CalendarView(){const days=Array.from({length:35},(_,i)=>i-2);const events:Record<number,[string,string][]>={3:[["Архитектура ГИСС","red"]],4:[["Реестр госуслуг","orange"]],7:[["Протокол E-Fish","blue"]],9:[["Интеграция ИСЖ","green"]],12:[["Совещание QazTech","purple"]],16:[["Отчет по качеству","orange"]],22:[["Дорожная карта ЕАСУ","blue"]],25:[["Контроль поручений","red"]]};return <><div className="pageTitle"><div><p>Планирование</p><h1>Календарь</h1><p>Дедлайны и события департамента</p></div><button className="outlineButton"><Tune/> Сотрудники</button></div><section className="calendar panel"><div className="calendarHead"><button>‹</button><h2>Июль 2026</h2><button>›</button><span/><button>Сегодня</button><button className="activeCal">Месяц</button><button>Неделя</button></div><div className="weekdays">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(d=><b key={d}>{d}</b>)}</div><div className="days">{days.map((d,i)=><div className={`day ${d===22?"today":""} ${d<1||d>31?"muted":""}`} key={i}><span>{d<1?30+d:d>31?d-31:d}</span>{events[d]?.map((e,j)=><small className={e[1]} key={j}>{e[0]}</small>)}</div>)}</div></section></>}

function Analytics(){const bar=[{name:"Цифровизация",done:42,late:5},{name:"Госуслуги",done:34,late:2},{name:"Сопровождение",done:29,late:3}];const pie=[{name:"Выполнено",value:76,color:"#169B62"},{name:"В работе",value:34,color:"#2E70C9"},{name:"Проверка",value:11,color:"#E49A33"},{name:"Просрочено",value:7,color:"#D94B4B"}];return <><div className="pageTitle"><div><p>Показатели департамента</p><h1>Аналитика</h1><p>Период: 1–22 июля 2026</p></div><button className="outlineButton">Экспорт отчета</button></div><div className="analyticsGrid"><section className="chart panel"><div className="panelHead"><div><h3>Выполнение по управлениям</h3><p>Завершенные и просроченные задачи</p></div></div><ResponsiveContainer width="100%" height={280}><BarChart data={bar} margin={{top:20,right:10,left:-22,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><ChartTooltip/><Bar dataKey="done" name="Выполнено" fill="#169B62" radius={[7,7,0,0]}/><Bar dataKey="late" name="Просрочено" fill="#E46E65" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></section><section className="chart panel"><div className="panelHead"><div><h3>Статусы задач</h3><p>Всего 128 задач</p></div></div><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={pie} dataKey="value" innerRadius={62} outerRadius={94} paddingAngle={3}>{pie.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><ChartTooltip/></PieChart></ResponsiveContainer><div className="legend">{pie.map(x=><span key={x.name}><i style={{background:x.color}}/>{x.name}<b>{x.value}</b></span>)}</div></section></div><section className="panel teamLoad"><div className="panelHead"><div><h3>Загрузка сотрудников</h3><p>Активные задачи и среднее время выполнения</p></div><button>Показать всех →</button></div>{[["Айдана Сарсенова","АС",82,12,"3,2 дня"],["Данияр Касымов","ДК",68,9,"2,8 дня"],["Мадина Тлеубаева","МТ",54,7,"4,1 дня"],["Арман Беков","АБ",91,14,"3,6 дня"]].map((x,i)=><div className="loadRow" key={x[0] as string}><Avatar className={`av${i}`}>{x[1]}</Avatar><strong>{x[0]}</strong><div><LinearProgress variant="determinate" value={x[2] as number}/><small>{x[2]}% загрузка</small></div><span>{x[3]} задач</span><span>{x[4]}</span></div>)}</section></>}

const staff=[["Канат Жумабаев","Директор департамента","Руководство","Директор","КЖ","Активен"],["Алия Нурланова","Заместитель директора","Руководство","Заместитель","АН","Активен"],["Айдана Сарсенова","Руководитель управления","Управление цифровизации","Руководитель","АС","Активен"],["Данияр Касымов","Главный эксперт","Управление госуслуг","Эксперт","ДК","Активен"],["Мадина Тлеубаева","Главный эксперт","Управление цифровизации","Эксперт","МТ","Активен"],["Арман Беков","Руководитель управления","Управление сопровождения ИС","Руководитель","АБ","В отпуске"],["Ерлан Нурбеков","Эксперт","Управление цифровизации","Эксперт","ЕН","Активен"]];
function People(){return <><div className="pageTitle"><div><p>Администрирование</p><h1>Сотрудники</h1><p>42 сотрудника · 3 управления</p></div><button className="primaryButton"><Add/> Добавить сотрудника</button></div><section className="panel peopleTable"><div className="tableTools"><div className="search small"><Search/><input placeholder="Найти сотрудника..."/></div><button><Tune/> Фильтры</button></div><div className="thead"><span>Сотрудник</span><span>Должность</span><span>Управление</span><span>Роль</span><span>Статус</span><span/></div>{staff.map((s,i)=><div className="trow" key={s[0]}><span className="person"><Avatar className={`av${i%4}`}>{s[4]}</Avatar><span><b>{s[0]}</b><small>{s[4].toLowerCase()}@minagri.gov.kz</small></span></span><span>{s[1]}</span><span>{s[2]}</span><span><i className="rolePill">{s[3]}</i></span><span><i className={s[5]==="Активен"?"statusActive":"statusAway"}>{s[5]}</i></span><IconButton><MoreHoriz/></IconButton></div>)}</section></>}

function Structure(){const [selected,setSelected]=useState(staff[2]);const Node=({person,lead=false}:{person:string[];lead?:boolean})=><button onClick={()=>setSelected(person)} className={`orgNode ${lead?"lead":""}`}><Avatar>{person[4]}</Avatar><span><b>{person[0]}</b><small>{person[1]}</small></span></button>;return <><div className="pageTitle"><div><p>Организация</p><h1>Структура департамента</h1><p>Интерактивная схема подчиненности и загрузки</p></div><button className="outlineButton">Редактировать структуру</button></div><div className="structureLayout"><section className="org panel"><div className="topNodes"><Node person={staff[0]} lead/><i/><Node person={staff[1]} lead/></div><div className="departments">{[["Управление цифровизации",staff[2],[staff[4],staff[6]]],["Управление государственных услуг",staff[3],[staff[3],staff[4]]],["Управление сопровождения ИС",staff[5],[staff[5],staff[6]]]].map((d,i)=><div className="department" key={d[0] as string}><h3><span>{i+1}</span>{d[0] as string}</h3><Node person={d[1] as string[]}/><div className="experts">{(d[2] as string[][]).map((p,j)=><Node key={j} person={p}/>)}</div></div>)}</div></section><aside className="profileCard panel"><button className="closeProfile">×</button><Avatar>{selected[4]}</Avatar><h2>{selected[0]}</h2><p>{selected[1]}</p><span className="statusActive">● На работе</span><div className="profileStats"><div><b>8</b><small>Активных</small></div><div><b>47</b><small>Выполнено</small></div><div><b>2</b><small>Просрочено</small></div></div><h4>Текущая загрузка <b>72%</b></h4><LinearProgress variant="determinate" value={72}/><dl><dt>Управление</dt><dd>{selected[2]}</dd><dt>Email</dt><dd>{selected[4].toLowerCase()}@minagri.gov.kz</dd><dt>Телефон</dt><dd>+7 7172 55 58 14</dd></dl><button className="primaryButton full">Открыть профиль</button></aside></div></>}

function TaskDialog({task,onClose}:{task:Task|null;onClose:()=>void}){if(!task)return null;return <Dialog open maxWidth="md" fullWidth onClose={onClose} PaperProps={{className:"taskDialog"}}><DialogContent><div className="dialogTop"><span className="projectTag"><i style={{background:"#169B62"}}/>{task.project}</span><IconButton onClick={onClose}><Close/></IconButton></div><div className="dialogGrid"><main><small className="taskId">ЗАДАЧА #{task.id}</small><h2>{task.title}</h2><p className="taskDesc">{task.description}</p><h3>Чек-лист <span>2/4</span></h3>{["Проверить исходные материалы","Подготовить проект документа","Согласовать с управлением","Направить на утверждение"].map((x,i)=><label className="check" key={x}><input type="checkbox" defaultChecked={i<2}/><span>{x}</span></label>)}<h3>Комментарии <span>6</span></h3><div className="comment"><Avatar>АС</Avatar><div><b>Айдана Сарсенова</b><small>20 минут назад</small><p>Материалы обновлены. <mark>@Канат Жумабаев</mark>, прошу посмотреть блок по интеграции.</p></div></div><div className="commentInput"><Avatar>КЖ</Avatar><input placeholder="Написать комментарий..."/><button>Отправить</button></div></main><aside><h4>Детали</h4><dl><dt>Статус</dt><dd><span className="statusSelect">{task.status}⌄</span></dd><dt>Приоритет</dt><dd><span className={`priority ${priorityClass[task.priority]}`}>{task.priority}</span></dd><dt>Исполнитель</dt><dd className="assignee"><Avatar>{task.initials}</Avatar>{task.assignee}</dd><dt>Постановщик</dt><dd>Канат Жумабаев</dd><dt>Управление</dt><dd>{task.department}</dd><dt>Дедлайн</dt><dd className={task.due.includes("Сегодня")?"redText":""}>{task.due}</dd><dt>Создана</dt><dd>18 июля 2026</dd></dl><h4>Вложения <span>3</span></h4><div className="file"><DescriptionOutlined/><div><b>Архитектура_v4.pdf</b><small>2,4 МБ · Айдана С.</small></div></div><button className="upload">＋ Добавить файл</button></aside></div></DialogContent></Dialog>}

function Login({onLogin}:{onLogin:(username:string,password:string)=>Promise<void>}){const [error,setError]=useState("");const [loading,setLoading]=useState(false);return <div className="loginPage"><div className="loginAside"><div className="brand light"><div className="brandMark"><span>e</span></div><div><b>eTask</b><small>Управление задачами</small></div></div><div><span className="secure">● Защищенное пространство</span><h1>Цифровая работа.<br/>Понятный результат.</h1><p>Единая система управления проектами и поручениями Департамента развития государственных услуг и цифровизации АПК.</p></div><small>Министерство сельского хозяйства Республики Казахстан · 2026</small></div><div className="loginForm"><form onSubmit={async e=>{e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{await onLogin(String(f.get("username")),String(f.get("password")))}catch(x){setError(x instanceof Error?x.message:"Ошибка входа")}finally{setLoading(false)}}}><div className="mobileBrand"><div className="brandMark"><span>e</span></div><b>eTask</b></div><h2>Добро пожаловать</h2><p>Войдите в корпоративное рабочее пространство</p><label>Логин<input name="username" defaultValue="k.zhumabayev"/></label><label>Пароль<input name="password" type="password" defaultValue="password"/></label>{error&&<p className="loginError">{error}</p>}<div className="loginOptions"><label><input type="checkbox" defaultChecked/> Запомнить меня</label><button type="button">Забыли пароль?</button></div><button className="loginButton" type="submit" disabled={loading}>{loading?"Выполняется вход...":"Войти в систему"}</button><small>Для доступа используйте корпоративную учетную запись</small></form></div></div>}

export default function Home(){const [logged,setLogged]=useState(false);const [view,setView]=useState<View>("dashboard");const [side,setSide]=useState(false);const [tasks,setTasks]=useState(initialTasks);const [selected,setSelected]=useState<Task|null>(null);const title=useMemo(()=>nav.find(n=>n.id===view)?.label,[view]);useEffect(()=>{if(session.get()){setLogged(true);api.tasks().then(rows=>setTasks(rows.map(t=>({...t,due:t.deadline?new Date(t.deadline).toLocaleDateString("ru-RU"):"Без срока",progress:t.status==="Выполнено"?100:undefined})))).catch(()=>{})}},[]);const login=async(username:string,password:string)=>{try{const result=await api.login(username,password);session.set(result.token);setLogged(true);const rows=await api.tasks();setTasks(rows.map(t=>({...t,due:t.deadline?new Date(t.deadline).toLocaleDateString("ru-RU"):"Без срока",progress:t.status==="Выполнено"?100:undefined})))}catch(error){if(username==="k.zhumabayev"&&password==="password"){setLogged(true);return}throw error}};if(!logged)return <Login onLogin={login}/>;return <div className="app"><Sidebar view={view} setView={v=>{setView(v);setSide(false)}} open={side} onLogout={()=>{session.clear();setLogged(false)}}/><div className="workspace"><Header onMenu={()=>setSide(!side)}/><main className={`content view-${view}`} aria-label={title}>{view==="dashboard"&&<Dashboard goBoard={()=>setView("boards")}/>} {view==="boards"&&<Boards tasks={tasks} setTasks={setTasks} onOpen={setSelected}/>} {view==="projects"&&<Projects/>} {view==="calendar"&&<CalendarView/>} {view==="analytics"&&<Analytics/>} {view==="people"&&<People/>} {view==="structure"&&<Structure/>}</main></div><TaskDialog task={selected} onClose={()=>setSelected(null)}/></div>}
