CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE user_role AS ENUM ('admin','director','deputy','manager','expert');
CREATE TYPE user_status AS ENUM ('active','vacation','disabled');

CREATE TABLE departments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL UNIQUE,sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),username text NOT NULL UNIQUE,password_hash text NOT NULL,full_name text NOT NULL,position text NOT NULL,department_id uuid REFERENCES departments(id),role user_role NOT NULL,status user_status NOT NULL DEFAULT 'active',email text UNIQUE,phone text,initials varchar(4),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_sessions(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,color varchar(7) NOT NULL DEFAULT '#246BCE',description text,created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE boards(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tasks(id bigserial PRIMARY KEY,parent_task_id bigint REFERENCES tasks(id) ON DELETE CASCADE,board_id uuid REFERENCES boards(id) ON DELETE SET NULL,project_id uuid NOT NULL REFERENCES projects(id),department_id uuid NOT NULL REFERENCES departments(id),title text NOT NULL,description text NOT NULL DEFAULT '',creator_id uuid NOT NULL REFERENCES users(id),assignee_id uuid REFERENCES users(id),priority text NOT NULL CHECK(priority IN('Критический','Высокий','Средний','Низкий')),status text NOT NULL DEFAULT 'Новая' CHECK(status IN('Новая','Назначена','В работе','На проверке руководителя','На согласовании заместителя','На утверждении директора','Выполнена','Закрыта')),current_stage text NOT NULL DEFAULT 'Директор',return_reason text,return_count integer NOT NULL DEFAULT 0,stage_started_at timestamptz NOT NULL DEFAULT now(),deadline timestamptz,position integer NOT NULL DEFAULT 0,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE comments(id bigserial PRIMARY KEY,task_id bigint NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,author_id uuid NOT NULL REFERENCES users(id),body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE attachments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id bigint NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,uploader_id uuid NOT NULL REFERENCES users(id),original_name text NOT NULL,stored_name text NOT NULL UNIQUE,mime_type text NOT NULL,size_bytes bigint NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE task_history(id bigserial PRIMARY KEY,task_id bigint NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id),action text NOT NULL,changes jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE checklist_items(id bigserial PRIMARY KEY,task_id bigint NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,title text NOT NULL,completed boolean NOT NULL DEFAULT false,position integer NOT NULL DEFAULT 0);
CREATE TABLE notifications(id bigserial PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,task_id bigint REFERENCES tasks(id) ON DELETE CASCADE,type text NOT NULL,message text NOT NULL,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_logs(id bigserial PRIMARY KEY,actor_id uuid REFERENCES users(id) ON DELETE SET NULL,action text NOT NULL,target_type text NOT NULL,target_id text,details jsonb NOT NULL DEFAULT '{}',ip inet,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX user_sessions_user_idx ON user_sessions(user_id,expires_at); CREATE INDEX user_sessions_expiry_idx ON user_sessions(expires_at); CREATE INDEX tasks_assignee_idx ON tasks(assignee_id,status); CREATE INDEX tasks_department_idx ON tasks(department_id,status); CREATE INDEX tasks_deadline_idx ON tasks(deadline); CREATE INDEX tasks_parent_idx ON tasks(parent_task_id); CREATE INDEX comments_task_idx ON comments(task_id,created_at); CREATE INDEX attachments_task_idx ON attachments(task_id); CREATE INDEX notifications_user_idx ON notifications(user_id,read_at,created_at DESC); CREATE INDEX audit_logs_created_idx ON audit_logs(created_at DESC); CREATE INDEX audit_logs_actor_idx ON audit_logs(actor_id,created_at DESC);
